services:
  web:
    image: storecoach
    ports:
      - "6868:8080"
    restart: unless-stopped
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "6869:27017"
    volumes:
      - /mnt/hdd0/storecoach/db:/data/db
    restart: unless-stopped